### PR TITLE
syncronous timestamp cache

### PR DESCRIPTION
**Pull request by gagalago**
Use synchronous file system function to retrieve the timestamp of assets for cache bursting

### CODE REVIEW

**Comment by gagalago** [comment]
@niftylettuce I don't realy like to merge my own pull request. Can I have a pair review of my code ? 
If you think all is ok, you can also update the npm package.

**Comment by niftylettuce** [comment]
@gagalago I really don't have the time to pair review 😦

**Comment by niftylettuce** [comment]
release v0.2.9 to npm

**Comment by gagalago** [comment]
no problem, thanks

**Pull request merged**
